### ISSUE TITLE
New release on pypi?

### ISSUE THREAD

**Issue by jorants** [beeware/bugjar#28]
The current release on pypi is broken for python 3 since it imports `Tkinter`.
It might be time to do a release on pypi again?

**Comment by freakboy3742** [comment]
I'm hesitant to release Bugjar in it's current state - it's *really* buggy, Python 2 only, and using tkinter. 

Ironically, bugjar is what I wanted to write when I started writing Toga et al; but I've been a little distracted. Eventually, I hope to circle the wagon back and build this thing...
